FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install apt-utils
RUN apt-get -y install build-essential
RUN apt-get -y install git
RUN apt-get -y install libc-ares-dev
RUN apt-get -y install libgflags-dev
RUN apt-get -y install libgoogle-glog-dev
RUN apt-get -y install libgoogle-perftools-dev
RUN apt-get -y install libprotobuf-dev
RUN apt-get -y install protobuf-compiler
RUN apt-get -y install scons
RUN apt-get -y install sudo
RUN apt-get -y update
RUN apt-get -y upgrade
